-- 코드를 작성해주세요
WITH FIRST_GEN AS (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL),
SECOND_GEN AS (SELECT A.ID, A.PARENT_ID FROM ECOLI_DATA A JOIN FIRST_GEN ON A.PARENT_ID = FIRST_GEN.ID)
SELECT B.ID
FROM ECOLI_DATA B
JOIN SECOND_GEN ON B.PARENT_ID = SECOND_GEN.ID
ORDER BY B.ID;